spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED